version: 2
updates:
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: slevomat/coding-standard
    versions:
    - 6.4.1
    - 7.0.0
    - 7.0.1
    - 7.0.2
    - 7.0.3
  - dependency-name: phpunit/phpunit
    versions:
    - 8.5.14
  - dependency-name: squizlabs/php_codesniffer
    versions:
    - 3.5.8
