sudo: false

language: php

matrix:
  include:
    - name: 'PHP 7.2 Unit Test Suite With Locked Dependencies'
      php: '7.2'
    - name: 'PHP 7.2 Unit Test Suite With Lowest Dependencies'
      php: '7.2'
      env: dependencies=lowest
    - name: 'PHP 7.2 Unit Test Suite With Highest Dependencies'
      php: '7.2'
      env: dependencies=highest
    - name: 'PHP Nightly Unit Test Suite With Locked Dependencies'
      php: nightly
    - name: 'PHP Nightly Unit Test Suite With Highest Dependencies'
      php: nightly
      env: dependencies=lowest
    - name: 'PHP Nightly Unit Test Suite With Lowest Dependencies'
      php: nightly
      env: dependencies=highest

    - name: 'PHP 7.2 Integration Test Suite With Locked Dependencies'
      php: '7.2'
      env: integration=1
    - name: 'PHP 7.2 Integration Test Suite With Lowest Dependencies'
      php: '7.2'
      env: dependencies=lowest integration=1
    - name: 'PHP 7.2 Integration Test Suite With Highest Dependencies'
      php: '7.2'
      env: dependencies=highest integration=1
    - name: 'PHP Nightly Integration Test Suite With Locked Dependencies'
      php: nightly
      env: integration=1
    - name: 'PHP Nightly Integration Test Suite With Highest Dependencies'
      php: nightly
      env: dependencies=lowest integration=1
    - name: 'PHP Nightly Integration Test Suite With Lowest Dependencies'
      php: nightly
      env: dependencies=highest integration=1

before_install:
- phpenv config-rm xdebug.ini || echo "No xdebug config."

install:
- wget https://github.com/php-coveralls/php-coveralls/releases/download/v2.0.0/php-coveralls.phar
- chmod +x php-coveralls.phar

before_script:
  - travis_retry composer self-update
  - if [ -z "$dependencies" ]; then travis_retry composer install; fi;
  - if [ "$dependencies" = "lowest" ]; then travis_retry composer update --prefer-lowest -n; fi;
  - if [ "$dependencies" = "highest" ]; then travis_retry composer update -n; fi;

script:
  - if [ -z "$integration" ]; then phpdbg -qrr vendor/bin/phpunit --testsuite AsyncVirusScanUnitTestSuite --coverage-text --coverage-clover build/logs/clover.xml; fi;
  - if [ -z "$integration" ]; then vendor/bin/phpcs -s; fi;
  - if [ "$integration" = 1 ]; then phpdbg -qrr vendor/bin/phpunit --testsuite AsyncVirusScanIntegrationTestSuite --coverage-text --coverage-clover build/logs/clover.xml; fi;

after_success:
  - travis_retry php php-coveralls.phar
